language: python
python:
  - "2.6"
  - "2.7"
install:
  - "pip install -r requirements.txt"
  - "pip install -r requirements-dev.txt"
script:
  - "py.test --ds=testsettings subscription/tests.py --cov=subscription"
  - "flake8 subscription/"